export const metadata = {
  title: "目標達成アプリ",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="ja">
        <body>{children}</body>
      </html>
    </>
  );
}
